scrape_configs:


- job_name: json_exporter
  static_configs:
  - targets:
    - json_exporter:7979

- job_name: json_exporter_prusa_mini_version
  metrics_path: /probe
  scrape_interval: 1s
  params:
    module: ['mini_version']
    target: ["http://192.168.1.25:/api/version"]
  static_configs:
  - targets:
    - "json_exporter:7979"

- job_name: json_exporter_prusa_mini_printer
  metrics_path: /probe
  scrape_interval: 1s
  params:
    module: ['mini_printer']
    target: ["http://192.168.1.25:/api/printer"]
  static_configs:
  - targets:
    - "json_exporter:7979"

- job_name: json_exporter_prusa_mini_job
  metrics_path: /probe
  scrape_interval: 1s
  params:
    module: ['mini_job']
    target: ["http://192.168.1.25:/api/job"]
  static_configs:
  - targets:
    - "json_exporter:7979"
