---
# helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
# helm repo add stable https://charts.helm.sh/stable
# helm repo update
# helm upgrade je prometheus-community/prometheus-json-exporter --install --namespace prusa -f k8s/values.yaml

serviceMonitor:
  enabled: true
  defaults:
    interval: 1s
  targets:
  - name: prusa-mini-version
    url: http://PRUSA_MINI_HOST_ADDRESS:/api/version
    interval: 1s
    module: mini_version

  - name: prusa-mini-printer
    interval: 1s
    url: http://PRUSA_MINI_HOST_ADDRESS:/api/printer
    module: mini_printer

  - name: prusa-mini-job
    interval: 1s
    url: http://PRUSA_MINI_HOST_ADDRESS:/api/job
    module: mini_job

configuration:
  config: |
    ---
    modules:
      mini_version:
        headers:
          X-Api-Key: PRUSA_API_KEY
        metrics:
        - name: prusa_mini
          type: object
          path: '{ $.api }'
          labels:
            api_version: '{ $ }'
          values:
            api_version: 1.0
        - name: prusa_mini
          type: object
          path: '{ $.server }'
          labels:
            server_version: '{ $ }'
          values:
            server_version: 1.0
        - name: prusa_mini
          type: object
          path: '{ $.text }'
          labels:
            text: '{ $ }'
          values:
            name: 1.0
        - name: prusa_mini
          type: object
          path: '{ $.hostname }'
          labels:
            hostname: '{ $ }'
          values:
            hostname: 1.0
    # printer
      mini_printer:
        headers:
          X-Api-Key: PRUSA_API_KEY
        metrics:
        - name: prusa_mini_telemetry
          type: object
          path: '{ $.telemetry }'
          values:
            temp_bed_celsius: '{ $.temp-bed }'
        - name: prusa_mini_telemetry
          type: object
          path: '{ $.telemetry }'
          values:
            temp_nozzle_celsius: '{ $.temp-nozzle }'
        - name: prusa_mini_telemetry
          type: object
          path: '{ $.telemetry }'
          values:
            print_speed_percent: '{ $.print-speed }'
        - name: prusa_mini_telemetry
          type: object
          path: '{ $.telemetry }'
          values:
            z_height: '{ $.z-height }'
        - name: prusa_mini_telemetry
          type: object
          path: '{ $.telemetry }'
          labels:
            material: '{ $.material }'
          values:
            material: 1.0
    #################################3
        - name: prusa_mini_temperature_tool0
          type: object
          path: '{ $.temperature.tool0.actual }'
          labels:
            name: 'actual'
          values:
            celsius: '{ $ }'
        - name: prusa_mini_temperature_tool0
          type: object
          path: '{ $.temperature.tool0.target }'
          labels:
            name: 'target'
          values:
            celsius: '{ $ }'
        - name: prusa_mini_temperature_tool0
          type: object
          path: '{ $.temperature.tool0.display }'
          labels:
            name: 'display'
          values:
            celsius: '{ $ }'
        - name: prusa_mini_temperature_tool0
          type: object
          path: '{ $.temperature.tool0.offset }'
          labels:
            name: 'offset'
          values:
            celsius: '{ $ }'
        - name: prusa_mini_temperature_bed
          type: object
          path: '{ $.temperature.bed.actual }'
          labels:
            name: 'actual'
          values:
            celsius: '{ $ }'
        - name: prusa_mini_temperature_bed
          type: object
          path: '{ $.temperature.bed.target }'
          labels:
            name: 'target'
          values:
            celsius: '{ $ }'
        - name: prusa_mini_temperature_bed
          type: object
          path: '{ $.temperature.bed.offset }'
          labels:
            name: 'offset'
          values:
            celsius: '{ $ }'
    #################################3
        - name: prusa_mini_state
          type: object
          path: '{ $.state.text }'
          labels:
            text: '{ $ }'
          values:
            text: 1
        - name: prusa_mini_state
          type: object
          path: '{ $.state.flags.operational }'
          labels:
            name: 'operational'
          values:
            flags: '{ $ }'
        - name: prusa_mini_state
          type: object
          path: '{ $.state.flags.paused }'
          labels:
            name: 'paused'
          values:
            flags: '{ $ }'
        - name: prusa_mini_state
          type: object
          path: '{ $.state.flags.cancelling }'
          labels:
            name: 'cancelling'
          values:
            flags: '{ $ }'
        - name: prusa_mini_state
          type: object
          path: '{ $.state.flags.pausing }'
          labels:
            name: 'pausing'
          values:
            flags: '{ $ }'
        - name: prusa_mini_state
          type: object
          path: '{ $.state.flags.sdReady }'
          labels:
            name: 'sdReady'
          values:
            flags: '{ $ }'
        - name: prusa_mini_state
          type: object
          path: '{ $.state.flags.error }'
          labels:
            name: 'error'
          values:
            flags: '{ $ }'
        - name: prusa_mini_state
          type: object
          path: '{ $.state.flags.closedOnError }'
          labels:
            name: 'closedOnError'
          values:
            flags: '{ $ }'
        - name: prusa_mini_state
          type: object
          path: '{ $.state.flags.ready }'
          labels:
            name: 'ready'
          values:
            flags: '{ $ }'
        - name: prusa_mini_state
          type: object
          path: '{ $.state.flags.busy }'
          labels:
            name: 'busy'
          values:
            flags: '{ $ }'
    # job
      mini_job:
        headers:
          X-Api-Key: PRUSA_API_KEY
        metrics:
        - name: prusa_mini_job
          type: object
          path: '{ $.state }'
          labels:
            name: '{ $ }'
          values:
            state: 1
        - name: prusa_mini_job
          type: object
          path: '{ $.job.estimatedPrintTime }'
          values:
            estimatedPrintTime_seconds: '{ $ }'
        # can be an overkill due to labels
        - name: prusa_mini_job
          type: object
          path: '{ $.job.file }'
          labels:
            name: '{ $.name }'
            path: '{ $.name }'
            display: '{ $.name }'
          values:
            file: 1
        - name: prusa_mini_progress
          type: object
          path: '{ $.progress.completion }'
          values:
            percent: '{ $ }'
        - name: prusa_mini_progress
          type: object
          path: '{ $.progress.printTime }'
          labels:
            name: print_time
          values:
            seconds: '{ $ }'
        - name: prusa_mini_progress
          type: object
          path: '{ $.progress.printTimeLeft }'
          labels:
            name: print_time_left
          values:
            seconds: '{ $ }'
