{
 "title": "Prusa",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Zoom in", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Text",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prusa_mini_state_text) by (text)",
     "legendFormat": "{{text}}"
    }
   ]
  },
  {
   "title": "Tool0 Temp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(prusa_mini_temperature_tool0_celsius{name=\"actual\"}) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(prusa_mini_temperature_tool0_celsius{name=\"target\"}) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(prusa_mini_temperature_tool0_celsius{name=\"target\"}) by (name) - 5",
     "legendFormat": "margin_min"
    },
    {
     "expr": "sum(prusa_mini_temperature_tool0_celsius{name=\"target\"}) by (name) + 5",
     "legendFormat": "margin_max"
    }
   ]
  },
  {
   "title": "Tool0 Temp Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(prusa_mini_temperature_tool0_celsius{name=\"actual\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Z-height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "sum(prusa_mini_telemetry_z_height) by (z_height)",
     "legendFormat": "z-height"
    }
   ]
  },
  {
   "title": "Job Progress Print time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(prusa_mini_progress_seconds{name=\"print_time\"})",
     "legendFormat": "time lapsed"
    }
   ]
  },
  {
   "title": "Tool0 Temp avg 5min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(prusa_mini_temperature_tool0_celsius{name=\"actual\"}[5m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Progress time left",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prusa_mini_progress_seconds{name=\"print_time_left\"})",
     "legendFormat": "time left"
    }
   ]
  },
  {
   "title": "Tool0 Temp Min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(prusa_mini_temperature_tool0_celsius{name=\"actual\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Progress %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prusa_mini_progress_percent", "legendFormat": "progress" }
   ]
  },
  {
   "title": "Estimated Print Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prusa_mini_job_estimatedPrintTime_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bed Temp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(prusa_mini_temperature_bed_celsius{name=\"actual\"}) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(prusa_mini_temperature_bed_celsius{name=\"target\"}) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(prusa_mini_temperature_bed_celsius{name=\"target\"}) by (name) - 5",
     "legendFormat": "margin_min"
    },
    {
     "expr": "sum(prusa_mini_temperature_bed_celsius{name=\"target\"}) by (name) + 5",
     "legendFormat": "margin_max"
    }
   ]
  },
  {
   "title": "Bed Temp Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(prusa_mini_temperature_bed_celsius{name=\"actual\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job ETA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() + sum(prusa_mini_progress_seconds{name=\"print_time_left\"}))*1000",
     "legendFormat": "seconds_since_epoch"
    }
   ]
  },
  {
   "title": "Bed Temp Avg 5min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(prusa_mini_temperature_bed_celsius{name=\"actual\"}[5m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bed Temp Min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(prusa_mini_temperature_bed_celsius{name=\"actual\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Printer - State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Text",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(prusa_mini_state_text) by (text)",
     "legendFormat": "{{text}}"
    }
   ]
  },
  {
   "title": "State Flags",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 20 },
   "targets": [
    {
     "expr": "sum(prusa_mini_state_flags) by (name)",
     "legendFormat": "{{text}}"
    }
   ]
  },
  { "title": "Printer Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Tool0 Temp",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(prusa_mini_temperature_tool0_celsius) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bed Temp",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(prusa_mini_temperature_bed_celsius) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Job Progress %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "prusa_mini_progress_percent", "legendFormat": "progress" }
   ]
  },
  {
   "title": "Job Progress Print time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(prusa_mini_progress_seconds{name=\"print_time\"})",
     "legendFormat": "time lapsed"
    }
   ]
  },
  {
   "title": "Job Progress time left",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(prusa_mini_progress_seconds{name=\"print_time_left\"})",
     "legendFormat": "time left"
    }
   ]
  },
  {
   "title": "Estimated Print Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(prusa_mini_job_estimatedPrintTime_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prusa_mini_job_state) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gcode Name",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prusa_mini_job_file) by (display)",
     "legendFormat": "{{display}}"
    }
   ]
  },
  { "title": "Printer - Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Bed Temp",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(prusa_mini_telemetry_temp_bed_celsius)",
     "legendFormat": "bed"
    }
   ]
  },
  {
   "title": "Nozzle Temp",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(prusa_mini_telemetry_temp_nozzle_celsius)",
     "legendFormat": "nozzle"
    }
   ]
  },
  {
   "title": "Print speed %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 41 },
   "targets": [
    {
     "expr": "sum(prusa_mini_telemetry_print_speed_percent)",
     "legendFormat": "speed"
    }
   ]
  },
  {
   "title": "Z-height",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "sum(prusa_mini_telemetry_z_height) by (z_height)",
     "legendFormat": "z-height"
    }
   ]
  },
  {
   "title": "Material",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 41 },
   "targets": [
    {
     "expr": "sum(prusa_mini_telemetry_material) by (material)",
     "legendFormat": "{{material}}"
    }
   ]
  }
 ]
}